
CREATE SEQUENCE SEQ_RECEITA_TIPO_RECEITA_TI499;

CREATE TABLE TF_RECEITA_TIPO (
                RECEITA_TIPO_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                RECEITA_TP VARCHAR2(20) NOT NULL,
                CONSTRAINT PK_RECEITA_TIPO PRIMARY KEY (RECEITA_TIPO_ID)
);
COMMENT ON TABLE TF_RECEITA_TIPO IS 'Tabela para armazenar o tipo de receita.';
COMMENT ON COLUMN TF_RECEITA_TIPO.RECEITA_TIPO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_RECEITA_TIPO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_RECEITA_TIPO.RECEITA_TP IS 'Coluna para armazenar o tipo de receita.';


CREATE SEQUENCE SEQ_DESPESA_STATUS_DESPESA_971;

CREATE TABLE TF_RECEITA_STATUS (
                DESPESA_STATUS_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                RECEITA_ST VARCHAR2(10) NOT NULL,
                CONSTRAINT PK_RECEITA_STATUS PRIMARY KEY (DESPESA_STATUS_ID)
);
COMMENT ON TABLE TF_RECEITA_STATUS IS 'Tabela para armazenar o status da receita.';
COMMENT ON COLUMN TF_RECEITA_STATUS.DESPESA_STATUS_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_RECEITA_STATUS.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_RECEITA_STATUS.RECEITA_ST IS 'Coluna para armazenar a situação da receita.
Exemplo:
- Salário
- Aluguel recebido
- Prêmio
- Presente
- Vendas
- Outros';


CREATE SEQUENCE SEQ_DESPESA_TIPO_DESPESA_TI875;

CREATE TABLE TF_DESPESA_TIPO (
                DESPESA_TIPO_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                DESPESA_TP VARCHAR2(20) NOT NULL,
                CONSTRAINT PK_DESPESA_TIPO PRIMARY KEY (DESPESA_TIPO_ID)
);
COMMENT ON TABLE TF_DESPESA_TIPO IS 'Tabela para armazenar o tipo de despesa.';
COMMENT ON COLUMN TF_DESPESA_TIPO.DESPESA_TIPO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_DESPESA_TIPO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_DESPESA_TIPO.DESPESA_TP IS 'Coluna para armazenar o tipo de despesa.';


CREATE SEQUENCE SEQ_DESPESA_STATUS_DESPESA_686;

CREATE TABLE TF_DESPESA_STATUS (
                DESPESA_STATUS_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                DESPESA_ST VARCHAR2(10) NOT NULL,
                CONSTRAINT PK_DESPESA_STATUS PRIMARY KEY (DESPESA_STATUS_ID)
);
COMMENT ON TABLE TF_DESPESA_STATUS IS 'Tabela para armazenar o status da despesa.';
COMMENT ON COLUMN TF_DESPESA_STATUS.DESPESA_STATUS_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_DESPESA_STATUS.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_DESPESA_STATUS.DESPESA_ST IS 'Coluna para armazenar a situação do despesa.
Exemplo:
- Pago
- Pendente';


CREATE SEQUENCE SEQ_INVESTIMENTO_TIPO_INVES604;

CREATE TABLE TF_INVESTIMENTO_TIPO (
                INVESTIMENTO_TIPO_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                INVESTIMENTO_ID NUMBER NOT NULL,
                INVESTIMENTO_TP VARCHAR2(20) NOT NULL,
                CONSTRAINT PK_INVESTIMENTO_TIPO PRIMARY KEY (INVESTIMENTO_TIPO_ID)
);
COMMENT ON TABLE TF_INVESTIMENTO_TIPO IS 'Tabela para armazenar o tipo de investimento.';
COMMENT ON COLUMN TF_INVESTIMENTO_TIPO.INVESTIMENTO_TIPO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO_TIPO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_INVESTIMENTO_TIPO.INVESTIMENTO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO_TIPO.INVESTIMENTO_TP IS 'Coluna para armazenar o tipo de investimento.';


CREATE SEQUENCE SEQ_INVESTIMENTO_STATUS_INV905;

CREATE TABLE TF_INVESTIMENTO_STATUS (
                INVESTIMENTO_STATUS_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                INVESTIMENTO_DS VARCHAR2(10) NOT NULL,
                CONSTRAINT PK_INVESTIMENTO_STATUS PRIMARY KEY (INVESTIMENTO_STATUS_ID)
);
COMMENT ON TABLE TF_INVESTIMENTO_STATUS IS 'Tabela para armazenar o status do investimento.';
COMMENT ON COLUMN TF_INVESTIMENTO_STATUS.INVESTIMENTO_STATUS_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO_STATUS.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_INVESTIMENTO_STATUS.INVESTIMENTO_DS IS 'Coluna para armazenar a situação do investimento.
Exemplo:
- Ativo
- Inativo';


CREATE SEQUENCE SEQ_LOGIN_LOGIN_ID;

CREATE TABLE TF_LOGIN (
                LOGIN_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                USUARIO_NM VARCHAR2(30) NOT NULL,
                EMAIL_NM VARCHAR2(50) NOT NULL,
                SENHA_NM VARCHAR2(16) NOT NULL,
                CONSTRAINT PK_LOGIN PRIMARY KEY (LOGIN_ID)
);

COMMENT ON TABLE TF_LOGIN IS 'Tabela para cadastro login.';
COMMENT ON COLUMN TF_LOGIN.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';
COMMENT ON COLUMN TF_LOGIN.USUARIO_NM IS 'Coluna para cadastrar o nome do usuario para acesso ao App.';
COMMENT ON COLUMN TF_LOGIN.EMAIL_NM IS 'Coluna para armazenar o email.';
COMMENT ON COLUMN TF_LOGIN.SENHA_NM IS 'Coluna para armazenar a senha de acesso ao App.';


CREATE SEQUENCE SEQ_DESPESA_DESPESA_ID;

CREATE TABLE TF_DESPESA (
                DESPESA_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                DESPESA_TIPO_ID NUMBER NOT NULL,
                DESPESA_DS VARCHAR2(20),
                LOGIN_ID NUMBER NOT NULL,
                CONSTRAINT PK_DESPESA PRIMARY KEY (DESPESA_ID)
);
COMMENT ON TABLE TF_DESPESA IS 'Tabela para armazezenar as despesa.';
COMMENT ON COLUMN TF_DESPESA.DESPESA_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_DESPESA.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';
COMMENT ON COLUMN TF_DESPESA.DESPESA_TIPO_ID IS 'Coluna contendo o código identificador.';


CREATE SEQUENCE SEQ_DESPESA_EVENTO_DESPESA_935;

CREATE TABLE TF_DESPESA_EVENTO (
                DESPESA_EVENTO_NU NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                DESPESA_ID NUMBER NOT NULL,
                DESPESA_STATUS_ID NUMBER NOT NULL,
                VENCIMENTO_DESPESA_DT DATE NOT NULL,
                DESPESA_VL NUMBER(18,2) NOT NULL,
                CONSTRAINT PK_DESPESA_EVENTO PRIMARY KEY (DESPESA_EVENTO_NU)
);
COMMENT ON TABLE TF_DESPESA_EVENTO IS 'Tabela para armazenar o evento do despesa.';
COMMENT ON COLUMN TF_DESPESA_EVENTO.DESPESA_EVENTO_NU IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_DESPESA_EVENTO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_DESPESA_EVENTO.DESPESA_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_DESPESA_EVENTO.DESPESA_STATUS_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_DESPESA_EVENTO.VENCIMENTO_DESPESA_DT IS 'Coluna para armazenar a data que a despesar vencerá.';
COMMENT ON COLUMN TF_DESPESA_EVENTO.DESPESA_VL IS 'Coluna para armazenar o valor da despesa.';


CREATE SEQUENCE SEQ_INVESTIMENTO_INVESTIMEN179;

CREATE TABLE TF_INVESTIMENTO (
                INVESTIMENTO_TIPO_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                LOGIN_ID NUMBER NOT NULL,
                INVESTIMENTO_NM VARCHAR2(20) NOT NULL,
                INVESTIMENTO_DS VARCHAR2(50) NOT NULL,
                CONSTRAINT PK_INVESTIMENTO PRIMARY KEY (INVESTIMENTO_TIPO_ID)
);
COMMENT ON TABLE TF_INVESTIMENTO IS 'Tabela para armazenar os dados do investimento.';
COMMENT ON COLUMN TF_INVESTIMENTO.INVESTIMENTO_TIPO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_INVESTIMENTO.INVESTIMENTO_NM IS 'Coluna para armazenar o nome do investimento.';
COMMENT ON COLUMN TF_INVESTIMENTO.INVESTIMENTO_DS IS 'Coluna para armazenar dados da descrição do investimento.';


CREATE SEQUENCE SEQ_INVESTIMENTO_EVENTO_INV319;

CREATE TABLE TF_INVESTIMENTO_EVENTO (
                INVESTIMENTO_EVENTO_NU NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                INVESTIMENTO_STATUS_ID NUMBER NOT NULL,
                INVESTIMENTO_TIPO_ID NUMBER NOT NULL,
                INVESTIMENTO_VL NUMBER(18,2) NOT NULL,
                CONSTRAINT PK_INVESTIMENTO_EVENTO PRIMARY KEY (INVESTIMENTO_EVENTO_NU)
);
COMMENT ON TABLE TF_INVESTIMENTO_EVENTO IS 'Tabela para armazenar o evento do investimento.';
COMMENT ON COLUMN TF_INVESTIMENTO_EVENTO.INVESTIMENTO_EVENTO_NU IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO_EVENTO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_INVESTIMENTO_EVENTO.INVESTIMENTO_STATUS_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO_EVENTO.INVESTIMENTO_TIPO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_INVESTIMENTO_EVENTO.INVESTIMENTO_VL IS 'Coluna para armazenar o valor investido.';


CREATE SEQUENCE SEQ_RECEITA_RECEITA_ID;

CREATE TABLE TF_RECEITA (
                RECEITA_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                LOGIN_ID NUMBER NOT NULL,
                RECEITA_TIPO_ID NUMBER NOT NULL,
                RECEITA_DS VARCHAR2(50),
                CONSTRAINT PK_RECEITA PRIMARY KEY (RECEITA_ID)
);
COMMENT ON TABLE TF_RECEITA IS 'Coluna para armazenar a receita.';
COMMENT ON COLUMN TF_RECEITA.RECEITA_ID IS 'Coluna contendoo código identiicador.';
COMMENT ON COLUMN TF_RECEITA.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';
COMMENT ON COLUMN TF_RECEITA.RECEITA_TIPO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_RECEITA.RECEITA_DS IS 'Coluna para armazenar a descrição da receita.';


CREATE SEQUENCE SEQ_RECEITA_DESPESA_DESPESA_ID;

CREATE TABLE TF_RECEITA_DESPESA (
                DESPESA_ID NUMBER NOT NULL,
                RECEITA_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                CONSTRAINT PK_RECEITA_DESPESA PRIMARY KEY (DESPESA_ID, RECEITA_ID)
);
COMMENT ON TABLE TF_RECEITA_DESPESA IS 'Tabela associativa.';
COMMENT ON COLUMN TF_RECEITA_DESPESA.DESPESA_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_RECEITA_DESPESA.RECEITA_ID IS 'Coluna contendoo código identiicador.';
COMMENT ON COLUMN TF_RECEITA_DESPESA.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';


CREATE SEQUENCE SEQ_RECEITA_EVENTO_RECEITA_343;

CREATE TABLE TF_RECEITA_EVENTO (
                RECEITA_EVENTO_NU NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                RECEITA_ID NUMBER NOT NULL,
                DESPESA_STATUS_ID NUMBER NOT NULL,
                RECEITA_VL NUMBER(18,2) NOT NULL,
                CONSTRAINT PK_RECEITA_EVENTO PRIMARY KEY (RECEITA_EVENTO_NU)
);
COMMENT ON TABLE TF_RECEITA_EVENTO IS 'Tabela para armazenar o evento do receita.';
COMMENT ON COLUMN TF_RECEITA_EVENTO.RECEITA_EVENTO_NU IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_RECEITA_EVENTO.REGISTRO_DT IS 'Coluna para armazenar a data do registro.';
COMMENT ON COLUMN TF_RECEITA_EVENTO.RECEITA_ID IS 'Coluna contendoo código identiicador.';
COMMENT ON COLUMN TF_RECEITA_EVENTO.DESPESA_STATUS_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_RECEITA_EVENTO.RECEITA_VL IS 'Coluna para armazenar o valor da receita.';


CREATE SEQUENCE SEQ_DADO_PESSOAL_PESSOA_ID;

CREATE TABLE TF_DADO_PESSOAL (
                PESSOA_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                LOGIN_ID NUMBER NOT NULL,
                NOME_SOBRENOME_NM VARCHAR2(30) NOT NULL,
                NASCIMENTO_DT DATE NOT NULL,
                CPF_NU NUMBER(11),
                REGISTRO_GERAL_NU NUMBER(15),
                CONSTRAINT PK_DADO_PESSOAL PRIMARY KEY (PESSOA_ID)
);
COMMENT ON TABLE TF_DADO_PESSOAL IS 'Tabela para cadastro dos dados pessoais.';
COMMENT ON COLUMN TF_DADO_PESSOAL.PESSOA_ID IS 'Coluna contendo o numero identificador.';
COMMENT ON COLUMN TF_DADO_PESSOAL.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';
COMMENT ON COLUMN TF_DADO_PESSOAL.NOME_SOBRENOME_NM IS 'Coluna para armazenar o nome e sobrenome do usuário.';
COMMENT ON COLUMN TF_DADO_PESSOAL.NASCIMENTO_DT IS 'Coluna para armazenar a data de nascimento.';
COMMENT ON COLUMN TF_DADO_PESSOAL.CPF_NU IS 'Coluna para armazenar o número do CPF.';
COMMENT ON COLUMN TF_DADO_PESSOAL.REGISTRO_GERAL_NU IS 'Coluna para armazenar o número do RG.';


CREATE SEQUENCE SEQ_TELEFONE_TELEFONE_ID;

CREATE TABLE TF_TELEFONE (
                TELEFONE_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                PESSOA_ID NUMBER NOT NULL,
                DDI_NU NUMBER(5),
                DDD_NU VARCHAR2(3),
                TELEFONE_TP VARCHAR2(15),
                TELEFONE_NU NUMBER,
                CONSTRAINT PK_TELEFONE PRIMARY KEY (TELEFONE_ID)
);
COMMENT ON TABLE TF_TELEFONE IS 'Tabela para armazenar o telefone.';
COMMENT ON COLUMN TF_TELEFONE.TELEFONE_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_TELEFONE.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';
COMMENT ON COLUMN TF_TELEFONE.PESSOA_ID IS 'Coluna contendo o numero identificador.';
COMMENT ON COLUMN TF_TELEFONE.DDI_NU IS 'Coluna para armazenar o DDI (Discagem Direta Internacional)';
COMMENT ON COLUMN TF_TELEFONE.DDD_NU IS 'Coluna para armazenar o DDD (Discagem Direta à Distancia).';
COMMENT ON COLUMN TF_TELEFONE.TELEFONE_TP IS 'Coluna para armazenar tipo do telefone.
Exemplo:

- Celular
- Residencial
- Comercial';
COMMENT ON COLUMN TF_TELEFONE.TELEFONE_NU IS 'Coluna para armazenar o número do telefone do usuário.';


CREATE SEQUENCE SEQ_ENDERECO_ENDERECO_ID;

CREATE TABLE TF_ENDERECO (
                ENDERECO_ID NUMBER NOT NULL,
                REGISTRO_DT DATE NOT NULL,
                PESSOA_ID NUMBER NOT NULL,
                CEP_NU NUMBER(8),
                LOGRADOURO_NM VARCHAR2(30),
                LOGRADOURO_NU NUMBER(8),
                COMPLEMENTO_DS VARCHAR2(50),
                BAIRRO_NM VARCHAR2(20),
                ESTADO_AC VARCHAR2(2),
                CIDADE_NM VARCHAR2(20),
                CONSTRAINT PK_ENDERECO PRIMARY KEY (ENDERECO_ID)
);

COMMENT ON TABLE TF_ENDERECO IS 'Tabela para armazenar o endereço do usuario.';
COMMENT ON COLUMN TF_ENDERECO.ENDERECO_ID IS 'Coluna contendo o código identificador.';
COMMENT ON COLUMN TF_ENDERECO.REGISTRO_DT IS 'Coluna para armazenar a data do registro do dado.';
COMMENT ON COLUMN TF_ENDERECO.PESSOA_ID IS 'Coluna contendo o numero identificador.';
COMMENT ON COLUMN TF_ENDERECO.CEP_NU IS 'Coluna para armazenar o número do CEP.';
COMMENT ON COLUMN TF_ENDERECO.LOGRADOURO_NM IS 'Coluna para armazenar o nome do logradouro.';
COMMENT ON COLUMN TF_ENDERECO.LOGRADOURO_NU IS 'Coluna para armazenar o número do logradouro.';
COMMENT ON COLUMN TF_ENDERECO.COMPLEMENTO_DS IS 'Coluna para armazenar o complemento do endereço.';
COMMENT ON COLUMN TF_ENDERECO.BAIRRO_NM IS 'Coluna para armazenar o bairro.';
COMMENT ON COLUMN TF_ENDERECO.ESTADO_AC IS 'Coluna para armazenar o acrônimo do Estado.';
COMMENT ON COLUMN TF_ENDERECO.CIDADE_NM IS 'Coluna para armazenar o nome da cidade.';


ALTER TABLE TF_RECEITA ADD CONSTRAINT FK_RECEITA_TIPO_RECEITA
FOREIGN KEY (RECEITA_TIPO_ID)
REFERENCES TF_RECEITA_TIPO (RECEITA_TIPO_ID)
NOT DEFERRABLE;

ALTER TABLE TF_RECEITA_EVENTO ADD CONSTRAINT FK_RECEITA_STATUS_RECEITA_E72
FOREIGN KEY (DESPESA_STATUS_ID)
REFERENCES TF_RECEITA_STATUS (DESPESA_STATUS_ID)
NOT DEFERRABLE;

ALTER TABLE TF_DESPESA ADD CONSTRAINT FK_DESPESA_TIPO_DESPESA
FOREIGN KEY (DESPESA_TIPO_ID)
REFERENCES TF_DESPESA_TIPO (DESPESA_TIPO_ID)
NOT DEFERRABLE;

ALTER TABLE TF_DESPESA_EVENTO ADD CONSTRAINT FK_DESPESA_STATUS_DESPESA_E784
FOREIGN KEY (DESPESA_STATUS_ID)
REFERENCES TF_DESPESA_STATUS (DESPESA_STATUS_ID)
NOT DEFERRABLE;

ALTER TABLE TF_INVESTIMENTO ADD CONSTRAINT FK_INVESTIMENTO_TIPO_INVEST80
FOREIGN KEY (INVESTIMENTO_TIPO_ID)
REFERENCES TF_INVESTIMENTO_TIPO (INVESTIMENTO_TIPO_ID)
NOT DEFERRABLE;

ALTER TABLE TF_INVESTIMENTO_EVENTO ADD CONSTRAINT FK_INVESTIMENTO_STATUS_INVE586
FOREIGN KEY (INVESTIMENTO_STATUS_ID)
REFERENCES TF_INVESTIMENTO_STATUS (INVESTIMENTO_STATUS_ID)
NOT DEFERRABLE;

ALTER TABLE TF_DADO_PESSOAL ADD CONSTRAINT FK_LOGIN_DADO_PESSOAL
FOREIGN KEY (LOGIN_ID)
REFERENCES TF_LOGIN (LOGIN_ID)
NOT DEFERRABLE;

ALTER TABLE TF_RECEITA ADD CONSTRAINT FK_LOGIN_RECEITA
FOREIGN KEY (LOGIN_ID)
REFERENCES TF_LOGIN (LOGIN_ID)
NOT DEFERRABLE;

ALTER TABLE TF_INVESTIMENTO ADD CONSTRAINT FK_LOGIN_INVESTIMENTO
FOREIGN KEY (LOGIN_ID)
REFERENCES TF_LOGIN (LOGIN_ID)
NOT DEFERRABLE;

ALTER TABLE TF_DESPESA ADD CONSTRAINT FK_LOGIN_DESPESA
FOREIGN KEY (LOGIN_ID)
REFERENCES TF_LOGIN (LOGIN_ID)
NOT DEFERRABLE;

ALTER TABLE TF_RECEITA_DESPESA ADD CONSTRAINT FK_DESPESA_RECEITA_DESPESA
FOREIGN KEY (DESPESA_ID)
REFERENCES TF_DESPESA (DESPESA_ID)
NOT DEFERRABLE;

ALTER TABLE TF_DESPESA_EVENTO ADD CONSTRAINT FK_DESPESA_INVESTIMENTO_EVENTO
FOREIGN KEY (DESPESA_ID)
REFERENCES TF_DESPESA (DESPESA_ID)
NOT DEFERRABLE;

ALTER TABLE TF_INVESTIMENTO_EVENTO ADD CONSTRAINT FK_INVESTIMENTO_INVESTIMENT839
FOREIGN KEY (INVESTIMENTO_TIPO_ID)
REFERENCES TF_INVESTIMENTO (INVESTIMENTO_TIPO_ID)
NOT DEFERRABLE;

ALTER TABLE TF_RECEITA_EVENTO ADD CONSTRAINT FK_RECEITA_RECEITA_EVENTO
FOREIGN KEY (RECEITA_ID)
REFERENCES TF_RECEITA (RECEITA_ID)
NOT DEFERRABLE;

ALTER TABLE TF_RECEITA_DESPESA ADD CONSTRAINT FK_RECEITA_RECEITA_DESPESA
FOREIGN KEY (RECEITA_ID)
REFERENCES TF_RECEITA (RECEITA_ID)
NOT DEFERRABLE;

ALTER TABLE TF_ENDERECO ADD CONSTRAINT FK_DADO_PESSOAL_ENDERECO
FOREIGN KEY (PESSOA_ID)
REFERENCES TF_DADO_PESSOAL (PESSOA_ID)
NOT DEFERRABLE;

ALTER TABLE TF_TELEFONE ADD CONSTRAINT FK_DADO_PESSOAL_TELEFONE
FOREIGN KEY (PESSOA_ID)
REFERENCES TF_DADO_PESSOAL (PESSOA_ID)
NOT DEFERRABLE;