-- LOGIN
INSERT INTO TF_login (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM,DESPESA_ID)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'MoniqueSouza', 'monique.souzas@gmail.com', '88q99'); 

INSERT INTO LOGIN (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM,DESPESA_ID)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL,CURRENT_DATE,'MARCELA','MARCELA@UOL.COM.BR','SENHA123');

INSERT INTO login (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM,DESPESA_ID)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'Eder', 'eder@gmail.com', '88q99'); 

INSERT INTO login (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM,DESPESA_ID)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'Julia', 'julia@gmail.com', '11447'); 

--DADOS PESSOAIS
INSERT INTO DADOS_PESSOAL
VALUES (SEQ_DADOS_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,4,'Monique Souza','07/07/1987', 012345678911,12345678);

INSERT INTO DADOS_PESSOAL (DADO_PESSOAL_ID,REGISTRO_DT,LOGIN_ID,NOME_SOBRENOME_NM,NASCIMENTO_DT,CPF_NU,REGISTRO_GERAL_NU)
VALUES (SEQ_DADOS_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,7,'MARCELA DOS SANTOS','11/01/2000',24875634751,2483541682);


--ENDERECO
INSERT INTO ENDERECO 
VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE,4, 04458040, 'Rua 12 de abril', 1, 'NULL', 'Jardim São Paulo', 'SP', 'SAO PAULO'); ENDEREÇO

INSERT INTO ENDERECO 
--VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE, 4, 04458040, 'Rua Numero 1', 1, 'Casa 2', 'Jardim Brasil', 'SP', 'SAO PAULO'); ENDEREÇO


--TELEFONE
INSERT INTO TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 2, 55, 011, 'CELULAR', 999999999);

INSERT INTO TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 4, 55, 011, 'CELULAR', 988555888);


--UPDATE
Alterar todos os dados do usuário, utilizando seu código como referência.
UPDATE LOGIN SET USUARIO_NM = 'Marcella' WHERE LOGIN_ID = 7;


--RECEITA
--Cadastrar as receitas do usuário.
INSERT INTO RECEITA_TIPO(RECEITA_TIPO_ID,REGISTRO_DT,RECEITA_TP)
VALUES (SEQ_DESPESA_TIPO_DESPESA_TIPO_ID.NEXTVAL,CURRENT_DATE,'SALARIO');

INSERT INTO RECEITA_TIPO(RECEITA_TIPO_ID,REGISTRO_DT,RECEITA_TP)
VALUES (2,to_date('11/03/2019','dd/mm/yyyy'),'INVESTIMENTO');

SELECT * FROM RECEITA
INSERT INTO RECEITA(RECEITA_ID,REGISTRO_DT,LOGIN_ID,RECEITA_TIPO_ID,RECEITA_DS)
VALUES (SEQ_RECEITA_RECEITA_ID.NEXTVAL, CURRENT_DATE,7,1,'SALARIO');

INSERT INTO RECEITA(RECEITA_ID,REGISTRO_DT,LOGIN_ID,RECEITA_TIPO_ID,RECEITA_DS)
VALUES (SEQ_RECEITA_RECEITA_ID.NEXTVAL, to_date('12/01/2020','dd/mm/yyyy'),7,2,'INVESTIMENTO');

--Cadastrar as despesas do usuário.

INSERT INTO DESPESA_TIPO(DESPESA_TIPO_ID,REGISTRO_DT,DESPESA_TP)
VALUES (SEQ_DESPESA_TIPO_DESPESA_TIPO_ID.NEXTVAL,CURRENT_DATE,'CONTA DE LUZ');

INSERT INTO DESPESA_TIPO(DESPESA_TIPO_ID,REGISTRO_DT,DESPESA_TP)
VALUES (SEQ_DESPESA_TIPO_DESPESA_TIPO_ID.NEXTVAL, CURRENT_DATE,'CONTA DE AGUA');


INSERT INTO DESPESA_STATUS(DESPESA_STATUS_ID,REGISTRO_DT,DESPESA_ST)
VALUES (SEQ_DESPESA_STATUS_DESPESA_STATUS_ID.NEXTVAL, CURRENT_DATE,'PAGO');

INSERT INTO DESPESA_STATUS(DESPESA_STATUS_ID,REGISTRO_DT,DESPESA_ST)
VALUES (SEQ_DESPESA_STATUS_DESPESA_STATUS_ID.NEXTVAL, CURRENT_DATE, 'ATRASADO');

SELECT * FROM DESPESA_TIPO
INSERT INTO DESPESA(DESPESA_ID,REGISTRO_DT,DESPESA_TIPO_ID,DESPESA_DS, LOGIN_ID, VENCIMENTO_DT)
VALUES (SEQ_DESPESA_DESPESA_ID.NEXTVAL,CURRENT_DATE,2,'CONTA DE LUZ',7,'12/01/2022');

--INVESTIMENTO
 --Cadastrar os dados para investimentos.


INSERT INTO INVESTIMENTO_TIPO(INVESTIMENTO_TIPO_ID,REGISTRO_DT,INVESTIMENTO_TP)
VALUES (SEQ_INVESTIMENTO_STATUS_INVESTIMENTO_STATUS_ID.NEXTVAL,CURRENT_DATE,'DAY TRADE');

INSERT INTO INVESTIMENTO_TIPO(INVESTIMENTO_TIPO_ID,REGISTRO_DT,INVESTIMENTO_TP)
VALUES (SEQ_INVESTIMENTO_TIPO_INVESTIMENTO_TIPO_ID.NEXTVAL,CURRENT_DATE,'SWING TRADE');

INSERT INTO INVESTIMENTO(INVESTIMENTO_ID, REGISTRO_DT, INVESTIMENTO_TIPO_ID, LOGIN_ID, INVESTIMENTO_NM, INVESTIMENTO_DS)
VALUES (1, CURRENTE_DATE, 1, 7,'DAY TRADE','DAY TRADE');


------------------------------------------------------------------------------------------------------
--COMANDOS DE SELECT  Consultas:

--Consultar os dados de um usuário (filtrar a partir do seu código).
SELECT * FROM LOGIN WHERE LOGIN_ID = 7;
SELECT * FROM LOGIN WHERE LOGIN_ID = 4;


--Consultar os dados de um único registro de despesa de um  usuário (filtrar a partir do código do usuário e do código da despesa).
SELECT * FROM RECEITA WHERE LOGIN_ID = 7;


--Consultar os dados de todos os registros de despesas de um  usuário, ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu código).
SELECT * FROM RECEITA WHERE LOGIN_ID = 7 ORDER BY REGISTRO_DT DESC;

--Consultar os dados de um único registro de investimento de um  usuário (filtrar a partir do código do usuário e do código de investimento.
SELECT * FROM INVESTIMENTO WHERE LOGIN_ID  = 7;

--Consultar os dados de todos os registros de investimentos de um  usuário, ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu código).
SELECT * FROM INVESTIMENTO WHERE LOGIN_ID = 7 ORDER BY REGISTRO_DT DESC;
  
--Consultar os dados básicos de um usuário, o último investimento registrado e a última despesa registrada (filtrar a partir do código de usuário – consulta necessária para o dashboard. Dica: veja consulta com junções).
 
SELECT * 
    FROM DADOS_PESSOAL ,INVESTIMENTO ,RECEITA
    WHERE DADOS_PESSOAL.LOGIN_ID = INVESTIMENTO.LOGIN_ID 
    AND RECEITA.LOGIN_ID = DADOS_PESSOAL.LOGIN_ID
    AND DADOS_PESSOAL.LOGIN_ID = 7
ORDER BY RECEITA.REGISTRO_DT DESC;





