-- LOGIN
INSERT INTO TF_LOGIN (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'MoniqueSouza', 'monique.souzas@gmail.com', '88q99'); 

INSERT INTO TF_LOGIN (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL,CURRENT_DATE,'MARCELA','MARCELA@UOL.COM.BR','SENHA123');

INSERT INTO TF_LOGIN (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'Eder', 'eder@gmail.com', '88q99'); 

INSERT INTO TF_LOGIN (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'Julia', 'julia@gmail.com', '11447'); 

INSERT INTO TF_LOGIN (LOGIN_ID,REGISTRO_DT,USUARIO_NM,EMAIL_NM,SENHA_NM)
VALUES (SEQ_LOGIN_LOGIN_ID.NEXTVAL, CURRENT_DATE, 'Gustavo', 'gustavo@gmail.com', '21141'); 


--DADOS PESSOAIS
INSERT INTO TF_DADO_PESSOAL
VALUES (SEQ_DADO_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,3,'Monique Souza','07/07/1987', 122233,122233);

INSERT INTO TF_DADO_PESSOAL
VALUES (SEQ_DADO_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,4,'MARCELA DOS SANTOS','11/01/2000',24875634751,2483541682);

INSERT INTO TF_DADO_PESSOAL
VALUES (SEQ_DADO_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,5,'Eder Sena','24/05/2000',1233,1233);


INSERT INTO TF_DADO_PESSOAL
VALUES (SEQ_DADO_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,6,'Julia Alcantara','12/02/2000',555555,555555);


INSERT INTO TF_DADO_PESSOAL
VALUES (SEQ_DADO_PESSOAL_PESSOA_ID.NEXTVAL,CURRENT_DATE,7,'Gustavo Ferreira','14/03/2001',1122233,112233);


--ENDERECO
INSERT INTO TF_ENDERECO (ENDERECO_ID, REGISTRO_DT, PESSOA_ID, CEP_NU,LOGRADOURO_NM, LOGRADOURO_NU, COMPLEMENTO_DS, BAIRRO_NM, CIDADE_NM)
VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE,3, 04458040, 'Rua 12 de abril', 1, 'NULL', 'Jardim São Paulo', 'SAO PAULO');

INSERT INTO TF_ENDERECO (ENDERECO_ID, REGISTRO_DT, PESSOA_ID, CEP_NU,LOGRADOURO_NM, LOGRADOURO_NU, COMPLEMENTO_DS, BAIRRO_NM, CIDADE_NM)
VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE,5, 04458040, 'Rua 1 de janeiro', 1, 'NULL', 'Jardim São Jorge', 'SAO PAULO');

INSERT INTO TF_ENDERECO (ENDERECO_ID, REGISTRO_DT, PESSOA_ID, CEP_NU,LOGRADOURO_NM, LOGRADOURO_NU, COMPLEMENTO_DS, BAIRRO_NM, CIDADE_NM)
VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE,6, 04458040, 'Rua 2 de fevereiro', 1, 'NULL', 'Jardim São Mateus', 'SAO PAULO');

INSERT INTO TF_ENDERECO (ENDERECO_ID, REGISTRO_DT, PESSOA_ID, CEP_NU,LOGRADOURO_NM, LOGRADOURO_NU, COMPLEMENTO_DS, BAIRRO_NM, CIDADE_NM)
VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE,9, 04458040, 'Rua 3 de marco', 1, 'NULL', 'Jardim São Pedro', 'SAO PAULO');

INSERT INTO TF_ENDERECO (ENDERECO_ID, REGISTRO_DT, PESSOA_ID, CEP_NU,LOGRADOURO_NM, LOGRADOURO_NU, COMPLEMENTO_DS, BAIRRO_NM, CIDADE_NM)
VALUES (SEQ_ENDERECO_ENDERECO_ID.NEXTVAL, CURRENT_DATE,10, 04458040, 'Rua 4 de maio', 1, 'NULL', 'Jardim São Cristovão', 'SAO PAULO');


--TELEFONE

INSERT INTO TF_TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 3, 55, 011, 'CELULAR', 999999999);

INSERT INTO TF_TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 5, 55, 011, 'CELULAR', 988555888);

INSERT INTO TF_TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 6, 55, 011, 'CELULAR', 911111111);

INSERT INTO TF_TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 9, 55, 011, 'CELULAR', 922222222);

INSERT INTO TF_TELEFONE 
VALUES (SEQ_TELEFONE_TELEFONE_ID.NEXTVAL, CURRENT_DATE, 10, 55, 011, 'CELULAR', 933333333);



--UPDATE
--Alterar todos os dados do usuário, utilizando seu código como referência.
UPDATE TF_LOGIN SET USUARIO_NM = 'Marcella' WHERE LOGIN_ID = 7;


--RECEITA
--Cadastrar as receitas do usuário.
INSERT INTO TF_RECEITA_TIPO(RECEITA_TIPO_ID,REGISTRO_DT,RECEITA_TP)
VALUES (SEQ_DESPESA_TIPO_DESPESA_TIPO_ID.NEXTVAL,CURRENT_DATE,'SALARIO');

select * from tf_receita_tipo;

INSERT INTO TF_RECEITA_TIPO(RECEITA_TIPO_ID,REGISTRO_DT,RECEITA_TP)
VALUES (4,to_date('11/03/2019','dd/mm/yyyy'),'POUPANCA');

SELECT * FROM TF_RECEITA;

INSERT INTO TF_RECEITA(RECEITA_ID,REGISTRO_DT,LOGIN_ID,RECEITA_TIPO_ID,RECEITA_DS)
VALUES (SEQ_RECEITA_RECEITA_ID.NEXTVAL, CURRENT_DATE,3,1,'SALARIO');

INSERT INTO TF_RECEITA(RECEITA_ID,REGISTRO_DT,LOGIN_ID,RECEITA_TIPO_ID,RECEITA_DS)
VALUES (SEQ_RECEITA_RECEITA_ID.NEXTVAL, to_date('12/01/2020','dd/mm/yyyy'),3,4,'INVESTIMENTO');

--Cadastrar as despesas do usuário.

INSERT INTO TF_DESPESA_TIPO(DESPESA_TIPO_ID,REGISTRO_DT,DESPESA_TP)
VALUES (SEQ_DESPESA_TIPO_DESPESA_TIPO_ID.NEXTVAL,CURRENT_DATE,'CONTA DE LUZ');

INSERT INTO TF_DESPESA_TIPO(DESPESA_TIPO_ID,REGISTRO_DT,DESPESA_TP)
VALUES (SEQ_DESPESA_TIPO_DESPESA_TIPO_ID.NEXTVAL, CURRENT_DATE,'CONTA DE AGUA');


INSERT INTO TF_DESPESA_STATUS(DESPESA_STATUS_ID,REGISTRO_DT,DESPESA_ST)
VALUES (SEQ_DESPESA_STATUS_DESPESA_STATUS_ID.NEXTVAL, CURRENT_DATE,'PAGO');

INSERT INTO TF_DESPESA_STATUS(DESPESA_STATUS_ID,REGISTRO_DT,DESPESA_ST)
VALUES (SEQ_DESPESA_STATUS_DESPESA_STATUS_ID.NEXTVAL, CURRENT_DATE, 'ATRASADO');

SELECT * FROM TF_DESPESA_TIPO
INSERT INTO TF_DESPESA(DESPESA_ID,REGISTRO_DT,DESPESA_TIPO_ID,DESPESA_DS, LOGIN_ID, VENCIMENTO_DT)
VALUES (SEQ_DESPESA_DESPESA_ID.NEXTVAL,CURRENT_DATE,2,'CONTA DE LUZ',7,'12/01/2022');

--INVESTIMENTO
 --Cadastrar os dados para investimentos.


INSERT INTO TF_INVESTIMENTO_TIPO(INVESTIMENTO_TIPO_ID,REGISTRO_DT,INVESTIMENTO_TP)
VALUES (SEQ_INVESTIMENTO_STATUS_INVESTIMENTO_STATUS_ID.NEXTVAL,CURRENT_DATE,'DAY TRADE');

INSERT INTO TF_INVESTIMENTO_TIPO(INVESTIMENTO_TIPO_ID,REGISTRO_DT,INVESTIMENTO_TP)
VALUES (SEQ_INVESTIMENTO_TIPO_INVESTIMENTO_TIPO_ID.NEXTVAL,CURRENT_DATE,'SWING TRADE');

INSERT INTO TF_INVESTIMENTO(INVESTIMENTO_ID, REGISTRO_DT, INVESTIMENTO_TIPO_ID, LOGIN_ID, INVESTIMENTO_NM, INVESTIMENTO_DS)
VALUES (1, CURRENTE_DATE, 1, 7,'DAY TRADE','DAY TRADE');


------------------------------------------------------------------------------------------------------
--COMANDOS DE SELECT  Consultas:

--Consultar os dados de um usuário (filtrar a partir do seu código).
SELECT * FROM TF_LOGIN WHERE LOGIN_ID = 7;
SELECT * FROM TF_LOGIN WHERE LOGIN_ID = 4;


--Consultar os dados de um único registro de despesa de um  usuário (filtrar a partir do código do usuário e do código da despesa).
SELECT * FROM TF_RECEITA WHERE LOGIN_ID = 7;


--Consultar os dados de todos os registros de despesas de um  usuário, ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu código).
SELECT * FROM TF_RECEITA WHERE LOGIN_ID = 7 ORDER BY REGISTRO_DT DESC;

--Consultar os dados de um único registro de investimento de um  usuário (filtrar a partir do código do usuário e do código de investimento.
SELECT * FROM TF_INVESTIMENTO WHERE LOGIN_ID  = 7;

--Consultar os dados de todos os registros de investimentos de um  usuário, ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu código).
SELECT * FROM TF_INVESTIMENTO WHERE LOGIN_ID = 7 ORDER BY REGISTRO_DT DESC;
  
--Consultar os dados básicos de um usuário, o último investimento registrado e a última despesa registrada (filtrar a partir do código de usuário – consulta necessária para o dashboard. Dica: veja consulta com junções).
 
SELECT * 
    FROM TF_DADOS_PESSOAL AS DP,TF_INVESTIMENTO AS INV,TF_RECEITA AS RCT
    WHERE DP.LOGIN_ID = INV.LOGIN_ID 
    AND RCT.LOGIN_ID = DP.LOGIN_ID
    AND DP.LOGIN_ID = 7
ORDER BY RCT.REGISTRO_DT DESC;